name: Build & Deploy with Approval

on:
  push:
    branches:
      - main  # main 브랜치 push 시 실행

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-jar
          path: build/libs/*.jar

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: must-approve-first  # 환경에 대한 승인 필요

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-jar

      - name: Decode SSH Key
        run: |
          printf '%s' "${{ secrets.DEV_SERVER_SSH_KEY_2 }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ec2-user
          key_path: ./private_key.pem
          port: 22
          source: /*.jar
          target: /home/ec2-user/app/spring/

      - name: Restart Spring Boot App
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ec2-user
          key_path: ./private_key.pem
          port: 22
          script: |
            # 포트 9090을 사용하는 기존 프로세스 종료
            PID=$(sudo lsof -ti tcp:9090 -sTCP:LISTEN)
            if [ -n "$PID" ]; then
              echo "Killing process on port 9090: $PID"
              sudo kill -9 $PID
            else
              echo "No process is using port 9090."
            fi

            # 새 JAR 실행
            nohup java -jar /home/ec2-user/app/spring/*.jar > /home/ec2-user/app/spring/app.log 2>&1 &
