name: Build & Deploy to Dev Server

on:
  push:
    branches:
      - main  # dev 브랜치 푸시 시 자동 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd gittest
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 4. Decode SSH Key (EC2 PEM)
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.DEV_SERVER_SSH_KEY }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      # 5. Copy JAR to Dev Server
      - name: Copy JAR to Dev Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: private_key.pem
          port: 22
          source: gittest/build/libs/*.jar
          target: /home/ec2-user/app/spring/

      # 6. Restart Spring Boot App
      - name: Restart Spring Boot App
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: private_key.pem
          port: 22
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar /home/ec2-user/app/spring/*.jar > /home/ec2-user/app/spring/app.log 2>&1 &
